{"name": "test_navigate_failure_reason", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message:", "trace": "self = <TestCases.Package_entity_management.TC_failure_reason.Test_Failure_Reason testMethod=test_navigate_failure_reason>\n\n    @allure.description(\"Should navigate to failure reason page\")\n    @allure.severity(severity_level=\"CRITICAL\")\n    @pytest.mark.order(7_01)\n    def test_navigate_failure_reason(self):\n        self.failure_reason =failure_reason(self.driver)\n>       self.failure_reason.navigate_failure_reason()\n\nTestCases/Package_entity_management/TC_failure_reason.py:32: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npage_objects/entity_Management/failure_reason.py:35: in navigate_failure_reason\n    if WebDriverWait(self.driver, 50).until(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"a1e33a1c2af5d516ffa88d5ea738f8fa\")>\nmethod = <function title_contains.<locals>._predicate at 0x7f9c10ea25f0>, message = ''\n\n    def until(self, method, message: str = \"\"):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message:\n\n../../.local/lib/python3.10/site-packages/selenium/webdriver/support/wait.py:95: TimeoutException"}, "description": "Should navigate to failure reason page", "start": 1678873785017, "stop": 1678873837008, "uuid": "7032fcb6-2ab9-460d-aa54-84e29a421e5e", "historyId": "d3a2215543b6cca0a90de3d9ecc5fa85", "testCaseId": "59576d8445db4d81725f7aacb7aebc1b", "fullName": "Test_Suites.test_all_module.Test_Failure_Reason#test_navigate_failure_reason", "labels": [{"name": "severity", "value": "CRITICAL"}, {"name": "tag", "value": "order(701)"}, {"name": "tag", "value": "@pytest.mark.usefixtures('init_driver')"}, {"name": "parentSuite", "value": "Test_Suites"}, {"name": "suite", "value": "test_all_module"}, {"name": "subSuite", "value": "Test_Failure_Reason"}, {"name": "host", "value": "sujith-HP-Compaq-Elite-8300-SFF"}, {"name": "thread", "value": "38359-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_Suites.test_all_module"}]}